version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: myriad-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadminpassword
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - app-network

  myriad-api:
    container_name: myriad-api
    image: myriadsocial/myriad-api:1a361e28e7bdf2a484c69f5b80a7a5b6c855891d
    restart: always
    ports:
      - "8081:3001"
    environment:
      - DOMAIN=api.testnet.myriad.social
      - PORT=3001
      # MYRIAD
      - MYRIAD_ADMIN_SUBSTRATE_MNEMONIC=
      - MYRIAD_ADMIN_NEAR_MNEMONIC=
      # JWT
      - JWT_TOKEN_SECRET_KEY=
      - JWT_TOKEN_EXPIRES_IN=36000
      - JWT_REFRESH_TOKEN_SECRET_KEY=
      - JWT_REFRESH_TOKEN_EXPIRES_IN=216000
      # MONGO
      - MONGO_PROTOCOL=mongodb
      - MONGO_HOST=myriad-mongo
      - MONGO_PORT=27017
      - MONGO_USER=root
      - MONGO_PASSWORD=password
      - MONGO_DATABASE=myriad
      - MONGO_URL=mongodb://root:password@myriad-mongo:27017/myriad?authSource=admin
      # REDIS
      - REDIS_CONNECTOR=
      - REDIS_HOST=
      - REDIS_PORT=
      - REDIS_PASSWORD=
      # SMTP
      - SMTP_SERVER=smtp.gmail.com
      - SMTP_PORT=465
      - SMTP_USERNAME=no-reply@myriad.systems
      - SMTP_PASSWORD=
      - SMTP_SENDER_ADDRESS=no-reply@myriad.systems
      # SENTRY
      - SENTRY_DSN=
      # TWITTER
      - TWITTER_API_KEY=
      # COIN MARKET CAP
      - COIN_MARKET_CAP_API_KEY=
    networks:
      - app-network
    depends_on:
      - mongodb
      - minio

  myriad-web:
    image: myriadsocial/myriad-web:6386e19c31c74b645be322fa5960941e6c0ce1e1
    restart: always
    container_name: myriad-web
    # Assuming it's a web service, expose the necessary port
    ports:
      - "8080:3000"
    depends_on:
      - myriad-api
    environment:
      - NODE_ENV=development
      - HOST=127.0.0.1
      - PORT=3000
      - NEXT_PUBLIC_APP_ENVIRONMENT=mainnet
      - NEXT_PUBLIC_APP_NAME=Myriad App
      - NEXT_PUBLIC_APP_VERSION=2.1.20
      - NEXTAUTH_URL=https://app.testnet.myriad.social
      - APP_SECRET=
      - NEXT_PUBLIC_MYRIAD_SUPPORT_MAIL=support@myriad.social
      - NEXT_PUBLIC_MYRIAD_WEBSITE_URL=https://myriad.social
      - NEXT_PUBLIC_MYRIAD_RPC_URL=wss://gateway.mainnet.octopus.network/myriad/a4cb0a6e30ff5233a3567eb4e8cb71e0
      - NEXT_PUBLIC_MYRIAD_API_URL=https://api.testnet.myriad.social
      - NEAR_TIPPING_CONTRACT_ID=myriadtips.near
      - NEXT_PUBLIC_SENTRY_DSN=
    networks:
      - app-network

volumes:
  mongodb_data:
  minio_data:

networks:
  app-network:
    driver: bridge